export const colourClassByName: Record<string, { bg: string; border: string }> = {
  slate: { bg: 'bg-slate-200', border: 'border-slate-400' },
  gray: { bg: 'bg-gray-200', border: 'border-gray-400' },
  zinc: { bg: 'bg-zinc-200', border: 'border-zinc-400' },
  neutral: { bg: 'bg-neutral-200', border: 'border-neutral-400' },
  stone: { bg: 'bg-stone-200', border: 'border-stone-400' },
  red: { bg: 'bg-red-200', border: 'border-red-400' },
  orange: { bg: 'bg-orange-200', border: 'border-orange-400' },
  amber: { bg: 'bg-amber-200', border: 'border-amber-400' },
  yellow: { bg: 'bg-yellow-200', border: 'border-yellow-400' },
  lime: { bg: 'bg-lime-200', border: 'border-lime-400' },
  green: { bg: 'bg-green-200', border: 'border-green-400' },
  emerald: { bg: 'bg-emerald-200', border: 'border-emerald-400' },
  teal: { bg: 'bg-teal-200', border: 'border-teal-400' },
  cyan: { bg: 'bg-cyan-200', border: 'border-cyan-400' },
  sky: { bg: 'bg-sky-200', border: 'border-sky-400' },
  blue: { bg: 'bg-blue-200', border: 'border-blue-400' },
  indigo: { bg: 'bg-indigo-200', border: 'border-indigo-400' },
  violet: { bg: 'bg-violet-200', border: 'border-violet-400' },
  purple: { bg: 'bg-purple-200', border: 'border-purple-400' },
  fuchsia: { bg: 'bg-fuchsia-200', border: 'border-fuchsia-400' },
  pink: { bg: 'bg-pink-200', border: 'border-pink-400' },
  rose: { bg: 'bg-rose-200', border: 'border-rose-400' },
}